version: '3.8'

services:
  icloud-mcp-server:
    build: 
      context: .
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
        - linux/arm64
    container_name: icloud-mcp-server
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
      - ICLOUD_USERNAME=${ICLOUD_USERNAME:-your.email@icloud.com}
      - ICLOUD_APP_PASSWORD=${ICLOUD_APP_PASSWORD:-your-app-specific-password}
    # For stdio communication with Claude
    stdin_open: true
    tty: true
    # Optional: expose port for HTTP MCP transport
    ports:
      - "${MCP_SERVER_PORT:-8081}:8080"
    # Health check
    healthcheck:
      test: ["CMD", "python", "-c", "print('Container is healthy')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    # Resource limits for Raspberry Pi
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '1.0'
        reservations:
          memory: 256M
          cpus: '0.5'